### ISSUE TITLE
Wiring plan + electrical components

### ISSUE THREAD

**Issue by Neodyn** [IzeHouze/A-10C-UFC#1]
It is also possible to create a wiring plan and a list of the electrical components

**Comment by IzeHouze** [comment]
Hi there!  

Wiring diagrams are already in this Git.  Kikad diagrams.  Parts should be labeled correctly in diagram.
https://github.com/IzeHouze/A-10C-UFC/tree/master/A-10CV1.2/A-10C-UFC
